Add music store example
ballerina-platform/module-ballerinax-aws.redshift pull request #11
Opened 2024-01-30 17:16 UTC by aashikam

## Purpose

Fixes:

## Examples

## Checklist
- [ ] Linked to an issue
- [ ] Updated the specification
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Checked native-image compatibility

2024-01-30 17:28 UTC, NipunaRanasinghe commented on examples/music-store/music_store/main.bal
> +redshift:Client dbClient = check new (jdbcUrl, user, password);
Do we need this, as there's another service-level redshift client initialised in L41?

2024-01-31 03:56 UTC, RDPerera requested changes

2024-01-31 03:56 UTC, RDPerera commented on examples/music-store/music_store.md
> +1. First, run the [`setup`](setup) ballerina program to set up the `MUSIC_STORE` database used in the sample. Execute the following command:
`[setup](setup)` Should this be linked to the setup folder? or it should be just `setup` like `music_store` ?

2024-02-06 04:39 UTC, niveathika approved these changes

2024-02-06 04:44 UTC, RDPerera approved these changes

2024-02-06 04:51 UTC, merged